### ISSUE TITLE
Exception when minifying file containing nested classes with same inner name

### ISSUE THREAD

**Issue by ThePadawan** [KvanTTT/CSharp-Minifier#27]
Exception is thrown in MinifyLocalsAstVisitor.VisitMember when the code to minify contains nested static classes, where an inner class has the same name as another in a different enclosing class.

MWE:

```
public static class A
{
    public static class One
    {
        public void foo() {}
    }
}

public static class B
{
    public static class One
    {
        public void foo() {}
    }
}
```

**Comment by KvanTTT** [comment]
@ThePadawan ok, I'll look at it. Is it critical for you, are you using this library?

**Comment by ThePadawan** [comment]
Not critical at all :). Was just playing around with the minifier.

**Comment by theCalcaholic** [comment]
I think I encounter the same bug. Can I help somehow to track it down?
Here's the Stacktrace:

[minifier_stacktrace.txt](https://github.com/KvanTTT/CSharp-Minifier/files/722236/minifier_stacktrace.txt)
