### ISSUE TITLE
Minifier breaks on base keyword

### ISSUE THREAD

**Issue by thomasdiemar** [KvanTTT/CSharp-Minifier#29]
I also want to use this for Space Engineers because of its character limit.

I've found this annoying error. The following throws a null pointer exception. It cant handle the base keyword.
```c#
    public class A
    {
        public virtual int M()
        {
            return -1;
        }
    }

    public class B : A 
    {
        public override int M()
        {
            return base.M();
        }
    }
```
So i cant really use inheritance, which is like... bummer in a OO environment...

A workaround could be nested classes, but it seems there is some issues with that approach also.

**Comment by KvanTTT** [comment]
@thomasdiemar, thank you for reporting!
