### ISSUE TITLE
Cant build current master

### ISSUE THREAD

**Issue by thomasdiemar** [KvanTTT/CSharp-Minifier#30]
Error	4	'ICSharpCode.NRefactory.CSharp.BaseReferenceExpression' is a 'type' but is used like a 'variable'	D:\GitSource\Repos\CSharp-Minifier\CSharpMinifier\Minifier.cs	813	33	CSharpMinifier

Error	1	The name 'nameof' does not exist in the current context	D:\GitSource\Repos\CSharp-Minifier\CSharpMinifier\Minifier.cs	811	21	CSharpMinifier

**Comment by thomasdiemar** [comment]
nm

**Comment by KvanTTT** [comment]
I updated project with new C# 6 version.
