### ISSUE TITLE
inherited protected methods not recognized correctly.

### ISSUE THREAD

**Issue by theCalcaholic** [KvanTTT/CSharp-Minifier#36]
"Compress members" breaks inheritance with protected members (parent class protected members are being renamed, child class protected (overriding) members arent).

    class Parent {
      protected virtual var someMethod() {
      }
    }
    class Child : Parent {
      protected override var someMethod {
      }
    }

results in:
`class b{protected virtual var a(){}}class c:b{protected override var someMethod{}}`

**Comment by KvanTTT** [comment]
This is a known issue, see also https://github.com/KvanTTT/CSharp-Minifier/issues/33 and https://github.com/KvanTTT/CSharp-Minifier/issues/32. Unfortunately I have no idea how it can be resolved with NRefactory. So, I close this issue as a duplicate.

**Comment by theCalcaholic** [comment]
Ah okay. Still, thanks for the work!
